<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT6KXRjx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT6KXRjx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT6KXRjx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT6KXRjx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT6KXRjx\App_KernelDevDebugContainer([
    'container.build_hash' => 'T6KXRjx',
    'container.build_id' => '354220df',
    'container.build_time' => 1646902582,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT6KXRjx');
