<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI6nP3Ob\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI6nP3Ob/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI6nP3Ob.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI6nP3Ob\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI6nP3Ob\App_KernelDevDebugContainer([
    'container.build_hash' => 'I6nP3Ob',
    'container.build_id' => 'd39e92ef',
    'container.build_time' => 1646903155,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI6nP3Ob');
